#include "base/cgraph_arr.c"
#include "base/cgraph_error.c"
#include "structure_generators.c"
#include "structural_properties.c"
#include "type_indexededgelist.c"
#include "visitors.c"
#include "foreign.c"